JK 11-end
friends-library/john-kendall pull request #51
Opened 2021-08-11 19:14 UTC by maijapapaya

@jaredh159 @Henderjay

2021-08-11 19:31 UTC, maijapapaya commented
So some things look a little funny but I wasn't sure what to do. I asked one of the questions in Slack because maybe you could find a better way to format it. The beginning of the stage entertainment chapter I wasn't sure about, and the end of the testimonies chapter I wasn't sure about either. :)

2021-08-12 13:22 UTC, jaredh159 requested changes
Thanks Maija, nice work on some difficult sections.  I left a few comments for a couple of changes. 👍

2021-08-12 13:22 UTC, jaredh159 commented on journal-letters/modernized/15-considerations-on-time.adoc
> +[quote.scripture, , 1 Thess. 5.]
yeah, i played around a bit with this on my computer, and i think it's both more correct and looks slightly better to make all 3 of these `quote.section-epigraph`

2021-08-12 13:22 UTC, jaredh159 commented on journal-letters/modernized/15-considerations-on-time.adoc
> +[.offset]
And this is a pretty good (i think) use-case for `.section-date`

2021-08-12 13:22 UTC, jaredh159 commented on journal-letters/modernized/16-on-stage-entertainment.adoc
> +[.blurb]
Ok, so this whole intro section was pretty difficult.  I definitely think that this "Submitted..." chunk qualifies as a "Heading Continuation Blurb" (which is in the styleguide, but rarely used -- and often I mark those up before they get to you.

Anyway, I pulled this down and tried a few variations and I think I'll have you while your making the other changes, just change this whole section to what I paste below:

```ASCIIDOC
== Remarks on the Prevailing Custom of Attending Stage Entertainments

[.heading-continuation-blurb]
Also on the Present Taste for Reading Romances and Novels; and on some other Customs

[.heading-continuation-blurb]
Submitted, with a heart overflowing with good-will,
to the notice and consideration of the Professors of the Christian name,
in the different religious Societies.

[.centered]
_Vitarc peccatum, est vitare occasioncs peccati._

[.section-author-context]
Reprinted from the Third Edition.

=== Remarks, etc.
```

2021-08-14 20:12 UTC, jaredh159 approved these changes

2021-08-14 20:13 UTC, merged

2021-08-14 20:13 UTC, jaredh159 commented
thanks maija, merged 👍